-- Create bookings table
CREATE TABLE bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT NOT NULL,
    email TEXT,
    seva_id TEXT,
    seva_name TEXT NOT NULL,
    seva_price INTEGER NOT NULL,
    date TEXT NOT NULL,
    gothra TEXT,
    nakshathra TEXT,
    count INTEGER NOT NULL DEFAULT 1,
    total_price INTEGER NOT NULL,
    payment_status TEXT DEFAULT 'Pending Verification',
    message TEXT,
    transaction_id TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create godana_payments table
CREATE TABLE godana_payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT NOT NULL,
    email TEXT,
    amount INTEGER NOT NULL,
    payment_id TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS (Optional, for now we use service role or public access for inserts)
-- For public insert access (standard for simple web forms without auth):
ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public anonymous insert" ON bookings FOR INSERT WITH CHECK (true);
CREATE POLICY "Admin full access" ON bookings USING (auth.role() = 'service_role');

ALTER TABLE godana_payments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public anonymous insert" ON godana_payments FOR INSERT WITH CHECK (true);
CREATE POLICY "Admin full access" ON godana_payments USING (auth.role() = 'service_role');
